### ISSUE TITLE
Words with special characters being missed when printing via the web interface

### ISSUE THREAD

**Issue by glynhudson** [openenergymonitor/BigCommerceAPI_OrderAddressLabelPrint#3]
Hi @emrysr 

The web interface is up and running in the office, it's working well. However, we've noticed one little bug.

Words with special characters are not printed when using the web interface when printing directly from the script the word prints correctly. I will send an image illustrating the issue via email since it contains a customer address. 

Could this be a character set issues on the web application

**Comment by emrysr** [comment]
The pdf is not created in PHP. It is all handled via the ruby script...? not sure what might be causing this.

I can't get it to run anymore! I get ruby errors in the command line:
```
$ ruby shop_download.rb
```
hits this error:
```
/usr/lib/ruby/2.5.0/net/http.rb:1616:in `addr_port': undefined method `include?' for nil:NilClass (NoMethodError)
```
When I run the ruby script via the web front end the PDF is not created but I can download (via `awaiting_fulfillment.rb`) the list of orders awaiting fulfillment. ?? so the call to the API must be working...

any ideas where I'm going wrong?

here's the full error message I get when I runrunning the script in the command line:

```
$ ruby shop_download.rb
Traceback (most recent call last):
        24: from shop_download.rb:20:in `<main>'
        23: from /usr/lib/ruby/2.5.0/csv.rb:1289:in `open'
        22: from shop_download.rb:23:in `block in <main>'
        21: from /var/lib/gems/2.5.0/gems/bigcommerce-1.0.1/lib/bigcommerce/resource_actions.rb:24:in `all'
        20: from /var/lib/gems/2.5.0/gems/bigcommerce-1.0.1/lib/bigcommerce/request.rb:47:in `get'
        19: from /var/lib/gems/2.5.0/gems/bigcommerce-1.0.1/lib/bigcommerce/request.rb:68:in `raw_request'
        18: from /var/lib/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:138:in `get'
        17: from /var/lib/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
        16: from /var/lib/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
        15: from /var/lib/gems/2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/request/encode_json.rb:24:in `call'
        14: from /var/lib/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/request/authorization.rb:37:in `call'
        13: from /var/lib/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
        12: from /var/lib/gems/2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/gzip.rb:24:in `call'
        11: from /var/lib/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:38:in `call'
        10: from /var/lib/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
         9: from /var/lib/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:43:in `block in call'
         8: from /var/lib/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:85:in `perform_request'
         7: from /usr/lib/ruby/2.5.0/net/http.rb:1213:in `get'
         6: from /usr/lib/ruby/2.5.0/net/http.rb:1455:in `request'
         5: from /usr/lib/ruby/2.5.0/net/http.rb:910:in `start'
         4: from /usr/lib/ruby/2.5.0/net/http.rb:1457:in `block in request'
         3: from /usr/lib/ruby/2.5.0/net/http.rb:1464:in `request'
         2: from /usr/lib/ruby/2.5.0/net/http.rb:1490:in `transport_request'
         1: from /usr/lib/ruby/2.5.0/net/http.rb:1551:in `begin_transport'
/usr/lib/ruby/2.5.0/net/http.rb:1616:in `addr_port': undefined method `include?' for nil:NilClass (NoMethodError)
```

I think my install of the gems is messed up...?

**Comment by emrysr** [comment]
I managed to re-create the PDF using an older version I had.... the CSV has all the characters showing correctly but the PDF doesn't.! 

> in my case it's a ö (U+00F6) http://www.fileformat.info/info/unicode/char/00F6/index.htm

If I print the label manually in gLabels all csv data is correctly displayed on the PDF..?

Not sure if this helps or makes things worse?..

**Comment by emrysr** [comment]
glabels-3-batch also works fine:
```
$ glabels-3-batch --input=/tmp/order_addresses.csv --output=/tmp/batch.pdf /tmp/MergeLabels.glabels
```
creates a PDF with all the non ascii characters in position

**Comment by emrysr** [comment]
@glynhudson - you were right
> ...Could this be a character set issues on the web application...

my version's broken, I can't successful test a copy of the master branch on my system (yet! 🤓)

## FIX:
add **`LC_ALL=en_GB.UTF-8 `** to index.php's `$command` variable to correct the character encoding:
```
$command = sprintf('LC_ALL=en_GB.UTF-8 ruby %s/shop_download.rb %....
```
[web/index.php#L35](https://github.com/openenergymonitor/BigCommerceAPI_OrderAddressLabelPrint/blob/master/web/index.php#L35)

## file access issue
the version I'm running also can't write to `/tmp` - probably my system ?? should be OK on a pi...

**Comment by glynhudson** [comment]
Hi @emrysr 

Thanks for investigation this. I made some change to the master branch so save `addresses.csv` and `output.csv` to `/tmp` as I was having dir permission errors when running the web app. I presumed `/tmp` would always be writable by all users and a good place to store temporary files. Do you think there is a better solution? I'm surprised that your system can write to `/tmp`.

Thanks I've applied the UTF change, we'll do some further testing this afternoon 👍
